### ISSUE TITLE
[DG] Update DG 

### ISSUE THREAD

**Issue by Ardentsoul** [AY2122S2-CS2103T-T09-3/tp#163]
## Details
Improve and fix the DG's relevant sections.

Things to edit for different people:
 - [x] WJ - show status (Line 365) & edit comment (Line 875), do follow the format as the rest have done
 - [x] SC - import export feature, add sequence diagrams (line 350), improve the feature further with more description and diagrams
 - [x] SC - importing/exporting trackmon data (Line 1025 onwards), improve the format further with more description
 - [x] KW - Sort, update the sort information when done with sort rework

**Comment by aweijun** [comment]
Hi, can I have an update regarding the comment command?
I am unsure of how to approach the situation as per discussed during the meeting, we seem to agree that the comment command is redundant considering that edit command does the same thing.

**Comment by JonathanHoshi** [comment]
> Hi, can I have an update regarding the comment command? I am unsure of how to approach the situation as per discussed during the meeting, we seem to agree that the comment command is redundant considering that edit command does the same thing.

I think we can leave it in first and decide whether we want to remove it after 1.3.

**Comment by JonathanHoshi** [comment]
Based on our disscussion privately, we have decided to remove the comment feature as edit already does what comment can do. Also, comment feel like a worser version of edit to use because of it being 7 letters to type instead of 4.
