### ISSUE TITLE
[PE-D] Suggestion to user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-3/tp#206]
"Double-click the file to start the app. The layout of Trackermon’s GUI is shown in the section below.
Do note that for Linux OS, you may have to enable double-click to run JAR files first!" - From the UG.

Take note that for mac systems, double clicking doesn't usually work and the user should input a command in the terminal ("java -jar Trackermon.jar") to run the application. 

The team can consider inputting this into the UG :)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: DannyDakota/ped#2

**Comment by JonathanHoshi** [comment]
We can take note of double clicking for mac system!

**Comment by arcornior** [comment]
Yep, noted! Will update the UG.
