### ISSUE TITLE
[PE-D] Edit command can add non unique names

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-3/tp#212]
![image.png](https://raw.githubusercontent.com/yongler/ped/main/files/4d0c5c72-e697-4ce1-a049-05cde141aafc.png)

manage to edit name to 'another' as compared to 'Another' 2nd movie, not fully unique and case insensitive

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yongler/ped#3

**Comment by JonathanHoshi** [comment]
I think we forgot to consider case-sensitivity when checking for unique names.
