### ISSUE TITLE
[PE-D] Sort by tag is a little buggy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-3/tp#222]
![image.png](https://raw.githubusercontent.com/NicsunXnus/ped/main/files/d17152f8-c358-4b80-887a-455f8e0e35db.png)

I used this test case to try out sort by tag in ascending order but it didn't work for me. I was expecting Show 2 to be before show 1. I am guessing that this is due to how alphabet sort works https://www.oncboces.org/Downloads/ALPHABETIZING%20RULES.pdf, but I feel that this may have caused the sorting feature to not work as expected.

![image.png](https://raw.githubusercontent.com/NicsunXnus/ped/main/files/3297746e-f74b-4b97-83e2-d6befa338ed8.png)

I used this test case to try out the descending order sort but unfortunately it looks it did not worked either.

edit: I just realised that sort by tags probably means sorting by the NUMBER of tags. It would be good if this was included in the UG. I am going to keep the severity at medium because I think this was pretty confusing.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: NicsunXnus/ped#3

**Comment by lowkaiwei98** [comment]
Agree we should make it more clear in UG
