### ISSUE TITLE
[PE-D] Suggestions to UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-3/tp#228]
![Screenshot 2022-04-01 at 2.55.49 PM.png](https://raw.githubusercontent.com/DannyDakota/ped/main/files/a9c9d23b-c0a7-4049-aed5-f7c4217dec54.png)

Maybe can expand more on this? In terms of the user, they may not be proficient with computers and thus may not be sure how to check for the java version

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DannyDakota/ped#6

**Comment by arcornior** [comment]
Noted, I'll try to see if I can find a SO answer and link it to this part, or failing that, come up with an additional section under it with more instructions.
