### ISSUE TITLE
[PE-D] Find command multiple parameters for r/

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-3/tp#235]
![image.png](https://raw.githubusercontent.com/yongler/ped/main/files/50cd3968-b01e-422f-9214-938081d899fa.png)

find r/2 3 results in find r/2, instead of whats stated in UG (invalid command)

![image.png](https://raw.githubusercontent.com/yongler/ped/main/files/0e07b7bd-21df-43c8-9cae-c72d2462c960.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yongler/ped#9

**Comment by Ardentsoul** [comment]
Yes, this is a UG mistake. I will fix it.
