### ISSUE TITLE
[PE-D] Documentation of JSON format in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-3/tp#246]
![Screenshot 2022-04-01 at 3.59.03 PM.png](https://raw.githubusercontent.com/DannyDakota/ped/main/files/ce4d8b6a-2236-4d9a-aa0f-b78f1eb1d9e0.png)

As your target user may not be tech savvy, they may not be able to understand what to do if json format is incorrect. Maybe can let them know what to do in case this occurs? Such as providing documentation on what the JSON format should be like so they can edit it accordingly

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DannyDakota/ped#10

**Comment by arcornior** [comment]
I agree with adding in documentation on how the JSON format should be like, allowing users to fix any corrupted JSON files.
This would likely take up a huge chunk of space in the UG, as I'll have to add in information on valid/invalid parameters for the different JSON fields. Good point!

**Comment by arcornior** [comment]
After much consideration, we have decided that users should not have to modify `trackermon.json`. More effort will be placed into ensuring that the files are stored correctly so users do not have to worry about invalid formats.
