### ISSUE TITLE
[Code Quality] Check and add comment for public class and methods

### ISSUE THREAD

**Issue by lowkaiwei98** [AY2122S2-CS2103T-T09-3/tp#282]
![image](https://user-images.githubusercontent.com/77216013/162011071-c448dd3c-ba46-47b4-a3a1-3352f07778cb.png)

i noticed some classes have no headers comment, please check briefly and add them.

- [x] Kaiwei
- [x] Shao Cong
- [x] Zac
- [x] Jon
- [x] Wei Jun

Missing Headers (Help me edit once it is updated) :
seedu.trackermon.commons.core.JarTools
seedu.trackermon.commons.model.show.exceptions.DuplicatedShowException
seedu.trackermon.commons.model.show.exceptions.ShowNotFoundException
seedu.trackermon.commons.model.show.Comment
seedu.trackermon.commons.model.show.Name
seedu.trackermon.commons.model.show.Rating
seedu.trackermon.commons.model.show.Status
seedu.trackermon.commons.model.show.UniqueShowList
seedu.trackermon.commons.model.util.ReadOnlyShowList
seedu.trackermon.commons.model.util.ShowList
seedu.trackermon.commons.storage.JsonFileManager
seedu.trackermon.commons.ui.CommandBuilder

test:
seedu.trackermon.commons.core.index.IndexTest
seedu.trackermon.commons.core.ConfigTest
seedu.trackermon.commons.core.GuiSettingTest
seedu.trackermon.commons.core.JarToolsTest
seedu.trackermon.commons.core.VersionTest
seedu.trackermon.commons.util.AppUtilTest
seedu.trackermon.commons.util.CollectionUtilTest
seedu.trackermon.commons.util.ConfigUtilTest
seedu.trackermon.commons.util.FileUtilTest
seedu.trackermon.commons.util.StringUtilTest
seedu.trackermon.commons.model.show.NameTest
seedu.trackermon.commons.model.show.ShowTest
seedu.trackermon.commons.model.show.UniqueShowListTest
seedu.trackermon.commons.model.tag.TagTest
seedu.trackermon.commons.storage.JsonSerializableShowListTest
seedu.trackermon.commons.storage.JsonShowListStorageTest
seedu.trackermon.commons.storage.JsonUserPrefsStorageTest
seedu.trackermon.commons.storage.StorageManageTest
seedu.trackermon.commons.testutil.ShowBuilder
seedu.trackermon.commons.testutil.TypicalShows
seedu.trackermon.commons.ui.CommandBuilderTest
seedu.trackermon.commons.ui.UiPartTest
seedu.trackermon.commons.AppParametersTest

**Comment by JonathanHoshi** [comment]
So are we adding header commands for all public main classes/methods and all public test classes/methods?

**Comment by lowkaiwei98** [comment]
Yes, as the image clearly state ALL public classes. I suggest we all check and add our own classes/method as the owner of the code can provide the most accurate and descriptive header.

**Comment by Ardentsoul** [comment]
These are the missing javadocs for the main class.
![image](https://user-images.githubusercontent.com/65216105/162133266-f9c7055b-d1c0-4973-a3d0-8db858b32436.png)

**Comment by lowkaiwei98** [comment]
Furthermore, according to https://github.com/nus-cs2103-AY2122S2/forum/issues/71, we need to write header comments for overridden methods too (my bad i thought it was fine before). Or at least put a @inheritDoc tag

**Comment by Ardentsoul** [comment]
@lowkaiwei98 I will fix the javadocs for the logic package in main first.

**Comment by lowkaiwei98** [comment]
ok noted
