### ISSUE TITLE
[Test] Application Lagging due to large number of character for comment

### ISSUE THREAD

**Issue by aweijun** [AY2122S2-CS2103T-T09-3/tp#283]
Added a comment with 1046605 characters, causing the whole application to lag.

![image](https://user-images.githubusercontent.com/95308604/162019839-b1e62c05-7178-4b3a-aa89-da88ebdbaec2.png)

Should we limit the number of characters a comment can have?

**Comment by lowkaiwei98** [comment]
Yes i think we should. If not they might bug report this during PE.

**Comment by JonathanHoshi** [comment]
I tested with 300k characters online at https://charactercounter.com/ with the copypasta i made at https://justpaste.it/3h1bz. What limit should we set for the character count?

**Comment by lowkaiwei98** [comment]
If 300k works well then we should just set 300k as the limit. Remember we need to state the limit in UG.

**Comment by Ardentsoul** [comment]
I agree with kw with regards to this.

**Comment by aweijun** [comment]
Hi, I was thinking if we should limit this to punctuations and alphanumerics.

**Comment by arcornior** [comment]
If other characters don't affect the max characters a comment can store I don't think there's a necessity to limit it to punctuations and alphanumerics.

**Comment by aweijun** [comment]
Hi, I have been testing this my current solution to this bug, at times the certain languages such as Korean would experience issues  and not be displayed. I feel that it would be safer to limit it to ascii characters, or alphanumeric characters and punctuations.

**Comment by lowkaiwei98** [comment]
Yes i agree, it will be safer to limit it. Remeber we had bug reports talking emoji and Japanese characters, so it's possiblely they might pull all sort of characters during PE.

**Comment by JonathanHoshi** [comment]
Sure, if other languages is causing an issue to the application, we should limit it to just be english itself.

**Comment by arcornior** [comment]
Yep, I had originally tested on Japanese and it didn't cause any issues so I neglected testing Korean. Great job catching this bug!
