### ISSUE TITLE
[Bug] Limit Name to 500 Characters.

### ISSUE THREAD

**Issue by aweijun** [AY2122S2-CS2103T-T09-3/tp#314]
## Details 
Similar to the issue with Tag, Name allows unlimited characters which would cause the system to lag. This is a ridiculously large number of characters so I think it should not happen under normal circumstances. But to be safe, I propose we fix it by limiting it as well. 

## Solution 
Limit it to 500 Characters.

**Comment by lowkaiwei98** [comment]
Yes. we should limit that too!

**Comment by arcornior** [comment]
Nice catch! Do remember to update the UG too!
