### ISSUE TITLE
[Release] Re-release v1.4b

### ISSUE THREAD

**Issue by JonathanHoshi** [AY2122S2-CS2103T-T09-3/tp#325]
## Details
Re-release v1.4b due to changes to DG and removing unused code.
- [x] Update DG page break
- [x] Update to correct version number 1.4.1
- [x] Re-release v1.4b

**Comment by arcornior** [comment]
Released [here](https://github.com/AY2122S2-CS2103T-T09-3/tp/releases/tag/v1.4b)!
