### ISSUE TITLE
Discuss Status class implementation

### ISSUE THREAD

**Issue by JonathanHoshi** [AY2122S2-CS2103T-T09-3/tp#63]
## Details
Currently our implementation of our status class is an enum class. Regarding this, what are your thoughts on this and what implementation should we use? 
- an enum class or
- a normal class with enum implementation or
- a pure normal class.

**Comment by arcornior** [comment]
@lowkaiwei98  I noticed that you're using a different implementation of Status from @aweijun's implementation.
Is there anything that you wish to address with your implementation?

**Comment by Ardentsoul** [comment]
I think either one of the 3 options are fine. Using a pure normal class is simpler, while using enum makes the code easier to read. So I think it would be up to the team's discretion on which implementation is 'better' or 'easier'.

**Comment by lowkaiwei98** [comment]
As discussed in our group telegram, pure normal class is simpler for me. Since we voted out enum class, we left with pure normal class and normal class with enum implementation. If you all want normal class with enum, we have decided on when to parse the string to enum.

**Comment by lowkaiwei98** [comment]
If we parse outside the class, there's not much different from using an enum class and in fact using an enum class makes more sense in this case.

**Comment by lowkaiwei98** [comment]
i only have a simple request to use a normal class... didn't expect yall to debate for hours...

**Comment by arcornior** [comment]
I came across [this discussion](https://stackoverflow.com/questions/9969690/whats-the-advantage-of-a-java-enum-versus-a-class-with-public-static-final-fiel) discussing the benefits of an enum class over a class with public constant fields. After reading through it, I'm of the mind that we should maintain the current Status implementation with an Enum class, what do you guys think?

**Comment by lowkaiwei98** [comment]
i felt like this had been dragged on and discussed for quite long for such a small issue and we even call a vote... i'm not against using enum class but can we just decide on one?

**Comment by aweijun** [comment]
Hi, Thanks for sharing the discussion that you found @arcornior, it was super helpful! The enumeration implementation seems to make sense to me as well! Would appreciate everyones thoughts on the difference between enum class and normal class with enum implementation!

**Comment by arcornior** [comment]
Since no one else seems to have an opinion, shall we keep our current implementation of Status for now? @lowkaiwei98 could you undo the changes to Status class and push again? If the need arises for Status to be implemented as a normal class we can bring this up again. Thanks everyone for your input!
